### PR TITLE
Pull request of cloning Branch

### PR DESCRIPTION
**Pull request by Goldinium**
This Project is part of Microverse program built with HTML5, CCS3 and bootstrap. The website is a clone project of "NewsWeek" front webpage, it is fully responsive with the help of  media query breakpoints.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Ben Benslama** 
Good job with the improvements for this project :muscle:  :muscle:
There are still some corrections to do before you can go ahead:

- [ ] Match the colors and structure of the original, login and subscribe should be in the same line, subscribe is a button with yellow background color:

| Yours | Original |
|:---:|:---:|
|image | image |

- [ ] The background color of the first navbar should be white.
- [ ] The first navbar should contain 11 links buts yours only contains 10
- [ ] You footer doesn't contain the social media icons
- [ ] The background color in SUBSCRIBE and NEWSLETTER sections should be white, not black

| Yours | Original |
|:---:|:---:|
|image | image |

- [ ] Your page should be responsive
- [ ] Next time, try to be more descriptive with your commit messages
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ]  Match the colors and structure of the original, login and subscribe should be in the same line, subscribe is a button with yellow background color: **This issue still persists**
> 
> Yours	Original
> image	image

| Clone | Original 
| --- | --- |
 | image | image |
| image | image |

- [ ]  Your page should be responsive **The page is not Fully responsive and is not changing accordingly to the original** 

### [Comments] :green_circle: 

- Use the browser media query inspector to observe the original website and try to mimic the responsiveness in the clone

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Goldinium  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Project description is great in your readme file, but it doesn't reflect what you did in this project, please work on it again and talk about what you have done, what you used and why you did it
- [ ] Pull request doesn't have description, please add it
- [ ] This project is incomplete, you are missing some sections : `The debate`, `More stories` => wrongly placed, `Editor's pick`, `Culture, sports, tech & Sciences`, ... sections. Please take a deep breath, sit, and work again on almost the whole project
- [x] Missing hamburger icon on the rightmost part of the navbar
- [ ] Subscribe button in navbar should have rounded corners
- [ ] The newsletter and subscribe section are messed up
- [ ] The footer is messed up on all screens
- [ ] The whole page is not responsive, as advice: try to compare your clone on desktop with the original page, and compare it when on medium screens and and compare it on smaller screens and make changes accondingly in order to make them look similar

# [Optional changes] :yellow_circle: 

- [ ] It will be nice if you implement the polygon which is on the bottom left of the navbar, just for learning purpose.

:warning: Your commit messages should be in imperative mode or present tense, _i.e.:_ you should have written `Work with the headerr section` instead of writing `working with the headerr section`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUIRED 🔴 ♻️ 
Hey team 👋 👋 good job on working on this project, it looks good. However, before marking it as `complete`, I will highlight some comments left by the previous TSE  ⬇️ 

- [ ] Project description is great in your readme file, but it doesn't reflect what you did in this project, please work on it again and talk about what you have done, what you used, and why you did it

- [ ]  Pull request doesn't have description, please add it

- [ ] Missing hamburger icon on the rightmost part of the navbar

- [ ] The newsletter and subscribe section are messed up

- [ ]  The footer is messed up on all screens

- [ ]  The whole page is not responsive, as advice: try to compare your clone on the desktop with the original page, and compare it when on medium screens and compare it on smaller screens and make changes accordingly in order to make them look similar

Kindly work on everything then submit another review when done.

Regards 
Peris Ndanu
Feel free to slack me if you have any questions

**Review by abredi — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @Goldinium, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏👏   I appreciate your hard work in replicating newsweek.com. Kindly fix the following issues.

[Required]

- [ ] This project requires to build a clone of the Newsweek.com homepage using the Bootstrap framework.
- [ ] The page should have a similar look to the source page. You have to replicate all sections, colors, alignments, etc...
- [ ] The page should be responsive as the source page for mobile,  tablet, desktop.

 
Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by Goldinium** [comment]
> ### Status: Require changes deciduous_tree ♲
> 
> Hi @Goldinium, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. clapclapclap I appreciate your hard work in replicating newsweek.com. Kindly fix the following issues.
> 
> [Required]
> 
>     * [ ]  This project requires to build a clone of the Newsweek.com homepage using the Bootstrap framework.
> 
>     * [ ]  The page should have a similar look to the source page. You have to replicate all sections, colors, alignments, etc...
> 
>     * [ ]  The page should be responsive as the source page for mobile,  tablet, desktop.
> 
> 
> Once you fix the issues, kindly submit another code review. ♲
> 
> Happy coding man_technologist
> [Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

for the first request, it is built using bootstrap indeed, did you check the source code?

**Review by ioilmio — CHANGES_REQUESTED** [review]
## Hello @Goldinium 👋🏽 
### I can see the effort but please fix the following issues:

### Required changes 🔴 
- ### The nav contains white Newsweek logo(image or svg);

- ### Top story, Featured stories, Advertisement, and other sections are not the same as on the original page, put them side to side, compare them and fix all the issue you can find;

- ### Editor's pick section: Images has a title overlay in red;

- ### In the magazine section: The first card have a different size compared to the other;

- ### Change your link color from blue to black;

- ### Respect the proportion and layout of the various sections;

- ### Make your commit messages more descriptive;

- ### Leverage Bootstrap power using its classes to style your project and use classes like sticky to scroll the top sections accordingly;

- ### Add a description for your Pull request;

- ### After changes, edit your readme file, with new screenshot and better linking;

- ### Quick advice: Start from mobile and move to tablet and finally desktop view screensize to style your project, always open both the original and your project together and comparing them, solve all the issues;


*For further info contact me on slack @illuminatosalvatore*

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Please work on the suggested changes by previous TSE

> ### Required changes 
- [ ] The nav contains white Newsweek logo(image or svg); **The logo is still black**
- [ ] Top story, Featured stories, Advertisement, and other sections are not the same as on the original page, put them side to side, compare them and fix all the issue you can find; **These sections don't follow the original website design**
> * [x] Editor's pick section: Images has a title overlay in red;
- [ ] In the magazine section: The first card has a different size compared to the other; **This issue still persists**
> * [x] Change your link color from blue to black;
- [ ] Respect the proportion and layout of the various sections; **This issue still persists**
- [ ] Make your commit messages more descriptive;
> * [x] Leverage Bootstrap power using its classes to style your project and use classes like sticky to scroll the top sections accordingly;
- [ ] Add a description for your Pull request; **Be more descriptive on the PR message, edit and update the description**
- [ ] After changes, edit your readme file, with new screenshot and better linking; **The style hasn't been updated**
- [ ] Quick advice: Start from mobile and move to tablet and finally desktop view screensize to style your project, always open both the original and your project together and comparing them, solve all the issues; **The project is not responsive. Not tablet nor mobile friendly. The project should move, hide elements accordingly to the original design. This is not happening**

Comparison images:

### Desktop

| Original | Clone |
| --- | --- |
| image | image |
| image | image |
| image | image |

### Tablet

| Original | Clone |
| --- | --- |
| image | image |
| image | image |
| image |
| ... Not going to show everything ... | ... Not going to show everything ... |

### Mobile 

| Original | Clone |
| --- | --- |
| image | image |
| ... Not going to show everything ... | ... Not going to show everything ... |








### [Comments] :green_circle: 

- Use the media query inspector to observe the original website responsive changes and apply them to the project.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi Team! 👋 👋 

#### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

_**Whilst you're addressing the comments of the previous TSE, be sure to use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) tool to help you with the font-family and font-size used in the actual site.**_

**Recommended**

- [ ] Make sure your project occupies more width on the screen like that of the actual site.
- [ ] The font-family used differs from the actual site, refer to my comment above.
- [ ] The 3 main columns need more work, refer to [Newsweek](newsweek.com) for more clarity.
- [ ] Most of the changes suggested by the previous TSE in the desktop screen size has not been implemented, please refer to his comments and work on them.
- [ ] The page on small screens also need a bit of work done to them, most of the issues has been addressed by the previous TSE, so refer to his comments as well.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ] Kindly work on the footer on a small screen  
Yours

The Original


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
#### Hello :wave: 
You still need to work on the footer like requested by the last reviewer, your footer still doesn't look like it is in the original website, especially the social links icons.
Please update accordingly and request another review.

slack(@ebeagusamuel)

**Review by eypsrcnuygr — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello @Goldinium. Your page looks pretty good and I think you've done a great job till here. However, before moving on, there are some things to be done.

- [ ] First of all, you can add a license section to your Readme. It'll make your repo more professional.
- [ ] The footer icons doesn't align correctly for mobile views.
wrong
The original:
right

- [ ] This section doesn't look good on mobile view. The characters are too big, the pictures don't show up. Kindly fix this.
wrong2
The original:
right2

- [ ] There is a gap on the right side of the page for the mobile view. Kindly fix this.
wrong3

### Optional:

- [ ] You can make a sticky header for your page. I think it'll make your page more identical to the original.
- [ ] You can change the general layout order for the mobile view. For this, you can refer to this [link.](https://getbootstrap.com/docs/4.1/utilities/flex/#order)

Again, it is a great work of art. :muscle: . If you do these changes it'll be much better.
After you make these changes please submit for a re-review.
Feel free to reach me via Slack, if you have any question. :100: 
_Eyüp Sercan UYGUR_

**Comment by eypsrcnuygr** [comment]
And also I forgot to mention that, please use imperative with your commit messages and try to be more clear with them. This is the general rule for the commit messages. Happy coding.

**Review by eypsrcnuygr — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello @Goldinium again. :smile_cat: 

You've changed the featured stories images, thanks for making the requested change. However, I said other changes also required as well. Please refer the last review and the comment after it and;

- [ ] Please fix the gap on the right side for the mobile view.(Under 990px)
- [ ] Please fix the order of the social icons on the footer.
- [ ] Please use imperative on your commit messages.
- [ ]  You can think about the optional changes and implement them for a good practice if you want.

Kindly make these changes and apply for a re-review.
If you have any question about the review, feel free to reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Review by eypsrcnuygr — APPROVED** [review]
## Status: Approved :partying_face: :tada: 
Hello @Goldinium. Your project has been approved. Congratulations. :+1: 

You pass all the mandatory requirements, there is no linter error and your page responds with the browser resize.
You can still think about adding the license section on your Readme as I said earlier. :100: 

Congratulations and good luck with the next projects.
_Eyüp Sercan UYGUR_

**Comment by Goldinium** [comment]
> ## Status: Approved partying_face tada
> 
> Hello @Goldinium. Your project has been approved. Congratulations. +1
> 
> You pass all the mandatory requirements, there is no linter error and your page responds with the browser resize.
> You can still think about adding the license section on your Readme as I said earlier. 100
> 
> Congratulations and good luck with the next projects.
> _Eyüp Sercan UYGUR_

Thank you, Done.

**Pull request merged**
